apiVersion: v1
kind: Namespace
metadata:
  name: eshop
  labels:
    app.kubernetes.io/name: eshop
    app.kubernetes.io/instance: eshop
---
apiVersion: v1
kind: Secret
metadata:
  namespace: eshop
  name: yoomoney-rest-api
type: Opaque
stringData:
  YOOMONEY_SHOP_ID: "{YOOMONEY_SHOP_ID}"
  YOOMONEY_SECRET_KEY: "{YOOMONEY_SECRET_KEY}"


